import type { SVGProps } from "react";
import {
  Globe as IconGlobe,
  Search as IconSearch,
  Bell as IconBell,
  User as IconUser,
  Users as IconUsers,
  Briefcase as IconBriefcase,
  Home as IconHome,
  LineChart as IconChart,
  Wallet as IconWallet,
  MessageSquare as IconMessage,
  Shield as IconShield,
  Settings as IconSettings,
  Star as IconStar,
  Check as IconCheck,
  ArrowRight as IconArrow,
  Plus as IconPlus,
  Filter as IconFilter,
  MapPin as IconLocation,
  Upload as IconUpload,
  Send as IconSend,
  FileText as IconFile,
  Paperclip as IconPaperclip,
  Lock as IconLock,
  Mail as IconMail,
  Eye as IconEye,
  EyeOff as IconEyeOff,
  Zap as IconBolt,
  Box as IconCube,
  Layers as IconLayers,
  Compass as IconCompass,
  Moon as IconMoon,
  Sun as IconSun,
  Menu as IconMenu,
  X as IconClose,
  LogOut as IconLogout,
  MoreHorizontal as IconMore,
  TrendingUp as IconTrend,
  CreditCard as IconCard,
  AlertTriangle as IconAlert,
  CircleDot as IconCircleDot,
  Clock as IconClock,
  Edit2 as IconEdit
} from "lucide-react";

export {
  IconGlobe,
  IconSearch,
  IconBell,
  IconUser,
  IconUsers,
  IconBriefcase,
  IconHome,
  IconChart,
  IconWallet,
  IconMessage,
  IconShield,
  IconSettings,
  IconStar,
  IconCheck,
  IconArrow,
  IconPlus,
  IconFilter,
  IconLocation,
  IconUpload,
  IconSend,
  IconFile,
  IconPaperclip,
  IconLock,
  IconMail,
  IconEye,
  IconEyeOff,
  IconBolt,
  IconCube,
  IconLayers,
  IconCompass,
  IconMoon,
  IconSun,
  IconMenu,
  IconClose,
  IconLogout,
  IconMore,
  IconTrend,
  IconCard,
  IconAlert,
  IconCircleDot,
  IconClock,
  IconEdit
};

type P = SVGProps<SVGSVGElement>;
const base = (props: P) => ({
  width: 20,
  height: 20,
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: 1.8,
  strokeLinecap: "round" as const,
  strokeLinejoin: "round" as const,
  ...props,
});

export const IconLogo = (p: P) => (
  <svg {...base(p)}>
    <path d="M3 12 12 3l9 9" />
    <path d="M5 10v10h14V10" />
    <path d="M9 20v-6h6v6" />
  </svg>
);
