export const NATIONALITIES = [
  "Afghan", "Albanian", "Algerian", "Argentine", "Armenian", "Australian",
  "Austrian", "Azerbaijani", "Bangladeshi", "Belarusian", "Belgian", "Bolivian",
  "Bosnian", "Brazilian", "British", "Bulgarian", "Cambodian", "Cameroonian",
  "Canadian", "Chilean", "Chinese", "Colombian", "Congolese", "Croatian", "Cuban",
  "Czech", "Danish", "Dutch", "Ecuadorian", "Egyptian", "Emirati", "English",
  "Estonian", "Ethiopian", "Finnish", "French", "Georgian", "German", "Ghanaian",
  "Greek", "Guatemalan", "Hungarian", "Indian", "Indonesian", "Iranian", "Iraqi",
  "Irish", "Israeli", "Italian", "Jamaican", "Japanese", "Jordanian", "Kazakh",
  "Kenyan", "Kuwaiti", "Lebanese", "Libyan", "Lithuanian", "Malaysian", "Mexican",
  "Mongolian", "Moroccan", "Nepalese", "New Zealander", "Nigerian", "Norwegian",
  "Omani", "Pakistani", "Palestinian", "Peruvian", "Philippine", "Polish",
  "Portuguese", "Qatari", "Romanian", "Russian", "Saudi", "Scottish", "Serbian",
  "Singaporean", "Slovak", "Slovenian", "Somali", "South African", "South Korean",
  "Spanish", "Sri Lankan", "Sudanese", "Swedish", "Swiss", "Syrian", "Taiwanese",
  "Tanzanian", "Thai", "Tunisian", "Turkish", "Ukrainian", "Uruguayan", "American",
  "Uzbek", "Venezuelan", "Vietnamese", "Yemeni", "Zimbabwean", "Other",
] as const;

const NATIONALITY_COUNTRY_CODES: Record<string, string> = {
  Afghan: "AF",
  Albanian: "AL",
  Algerian: "DZ",
  Argentine: "AR",
  Armenian: "AM",
  Australian: "AU",
  Austrian: "AT",
  Azerbaijani: "AZ",
  Bangladeshi: "BD",
  Belarusian: "BY",
  Belgian: "BE",
  Bolivian: "BO",
  Bosnian: "BA",
  Brazilian: "BR",
  British: "GB",
  Bulgarian: "BG",
  Cambodian: "KH",
  Cameroonian: "CM",
  Canadian: "CA",
  Chilean: "CL",
  Chinese: "CN",
  Colombian: "CO",
  Congolese: "CD",
  Croatian: "HR",
  Cuban: "CU",
  Czech: "CZ",
  Danish: "DK",
  Dutch: "NL",
  Ecuadorian: "EC",
  Egyptian: "EG",
  Emirati: "AE",
  English: "GB",
  Estonian: "EE",
  Ethiopian: "ET",
  Finnish: "FI",
  French: "FR",
  Georgian: "GE",
  German: "DE",
  Ghanaian: "GH",
  Greek: "GR",
  Guatemalan: "GT",
  Hungarian: "HU",
  Indian: "IN",
  Indonesian: "ID",
  Iranian: "IR",
  Iraqi: "IQ",
  Irish: "IE",
  Israeli: "IL",
  Italian: "IT",
  Jamaican: "JM",
  Japanese: "JP",
  Jordanian: "JO",
  Kazakh: "KZ",
  Kenyan: "KE",
  Kuwaiti: "KW",
  Lebanese: "LB",
  Libyan: "LY",
  Lithuanian: "LT",
  Malaysian: "MY",
  Mexican: "MX",
  Mongolian: "MN",
  Moroccan: "MA",
  Nepalese: "NP",
  "New Zealander": "NZ",
  Nigerian: "NG",
  Norwegian: "NO",
  Omani: "OM",
  Pakistani: "PK",
  Palestinian: "PS",
  Peruvian: "PE",
  Philippine: "PH",
  Polish: "PL",
  Portuguese: "PT",
  Qatari: "QA",
  Romanian: "RO",
  Russian: "RU",
  Saudi: "SA",
  Scottish: "GB",
  Serbian: "RS",
  Singaporean: "SG",
  Slovak: "SK",
  Slovenian: "SI",
  Somali: "SO",
  "South African": "ZA",
  "South Korean": "KR",
  Spanish: "ES",
  "Sri Lankan": "LK",
  Sudanese: "SD",
  Swedish: "SE",
  Swiss: "CH",
  Syrian: "SY",
  Taiwanese: "TW",
  Tanzanian: "TZ",
  Thai: "TH",
  Tunisian: "TN",
  Turkish: "TR",
  Ukrainian: "UA",
  Uruguayan: "UY",
  American: "US",
  Uzbek: "UZ",
  Venezuelan: "VE",
  Vietnamese: "VN",
  Yemeni: "YE",
  Zimbabwean: "ZW",
};

function countryCodeToFlag(code: string): string {
  if (code.length !== 2) return "";
  const upper = code.toUpperCase();
  return String.fromCodePoint(
    ...[...upper].map((char) => 0x1f1e6 + char.charCodeAt(0) - 65),
  );
}

export function getNationalityFlag(nationality: string | null | undefined): string {
  if (!nationality) return "";
  const code = NATIONALITY_COUNTRY_CODES[nationality.trim()];
  return code ? countryCodeToFlag(code) : "";
}
