/** Map nationality demonym (as stored in DB) to ISO 3166-1 alpha-2 for flag emoji. */
const DEMONYM_TO_ISO: Record<string, string> = {
  Afghan: "AF",
  Albanian: "AL",
  Algerian: "DZ",
  Argentine: "AR",
  Armenian: "AM",
  Australian: "AU",
  Austrian: "AT",
  Azerbaijani: "AZ",
  Bangladeshi: "BD",
  Belarusian: "BY",
  Belgian: "BE",
  Bolivian: "BO",
  Bosnian: "BA",
  Brazilian: "BR",
  British: "GB",
  Bulgarian: "BG",
  Cambodian: "KH",
  Cameroonian: "CM",
  Canadian: "CA",
  Chilean: "CL",
  Chinese: "CN",
  Colombian: "CO",
  Congolese: "CD",
  Croatian: "HR",
  Cuban: "CU",
  Czech: "CZ",
  Danish: "DK",
  Dutch: "NL",
  Ecuadorian: "EC",
  Egyptian: "EG",
  Emirati: "AE",
  English: "GB",
  Estonian: "EE",
  Ethiopian: "ET",
  Finnish: "FI",
  French: "FR",
  Georgian: "GE",
  German: "DE",
  Ghanaian: "GH",
  Greek: "GR",
  Guatemalan: "GT",
  Hungarian: "HU",
  Indian: "IN",
  Indonesian: "ID",
  Iranian: "IR",
  Iraqi: "IQ",
  Irish: "IE",
  Israeli: "IL",
  Italian: "IT",
  Jamaican: "JM",
  Japanese: "JP",
  Jordanian: "JO",
  Kazakh: "KZ",
  Kenyan: "KE",
  Kuwaiti: "KW",
  Lebanese: "LB",
  Libyan: "LY",
  Lithuanian: "LT",
  Malaysian: "MY",
  Mexican: "MX",
  Mongolian: "MN",
  Moroccan: "MA",
  Nepalese: "NP",
  "New Zealander": "NZ",
  Nigerian: "NG",
  Norwegian: "NO",
  Omani: "OM",
  Pakistani: "PK",
  Palestinian: "PS",
  Peruvian: "PE",
  Philippine: "PH",
  Polish: "PL",
  Portuguese: "PT",
  Qatari: "QA",
  Romanian: "RO",
  Russian: "RU",
  Saudi: "SA",
  Scottish: "GB",
  Serbian: "RS",
  Singaporean: "SG",
  Slovak: "SK",
  Slovenian: "SI",
  Somali: "SO",
  "South African": "ZA",
  "South Korean": "KR",
  Spanish: "ES",
  Sudanese: "SD",
  Swedish: "SE",
  Swiss: "CH",
  Syrian: "SY",
  Taiwanese: "TW",
  Tanzanian: "TZ",
  Thai: "TH",
  Tunisian: "TN",
  Turkish: "TR",
  Ukrainian: "UA",
  American: "US",
  Uruguayan: "UY",
  Uzbek: "UZ",
  Venezuelan: "VE",
  Vietnamese: "VN",
  Welsh: "GB",
  Yemeni: "YE",
  Zambian: "ZM",
  Zimbabwean: "ZW",
};

export function nationalityFlag(nationality: string): string {
  const iso = DEMONYM_TO_ISO[nationality.trim()];
  if (!iso || iso.length !== 2) return "🌍";
  const upper = iso.toUpperCase();
  return String.fromCodePoint(
    upper.charCodeAt(0) + 127397,
    upper.charCodeAt(1) + 127397,
  );
}
